def read_nums():
  a=input()
  a=int(a)
  b=input()
  b=int(b)
  c=input()
  c=int(c)
  #print(a,b,c)
  #print(a+b+c)
  print('input:',a,'square:',a**2)
  print('input:',b,'square:',b**2)
  print('input:',c,'square:',c**2)
  print('sum:',a+b+c)
  print('product:',a*b*c)
  print('square sum:',(a**2)+(b**2)+(c**2))
read_nums()  